[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Pauwels_Logger"
version = "0.1.0"
description = "Library to have a cool logger :D"
authors = [{name = "Tom Pauwels"}]
dependencies = []
